services:
  - type: web
    name: budgetmate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: budgetmate-db
          property: connectionString

databases:
  - name: budgetmate-db
    databaseName: budgetmate
    user: budgetmate_user
    plan: free 