services:
  - type: web
    name: budgetmate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: budgetmate-db
          property: connectionString

databases:
  - name: budgetmate-db
    databaseName: budgetmate
    user: budgetmate_user
    plan: free 